name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install build deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # editable install of our package
          pip install -e .

      - name: Run e2e with SKIP on online fail
        env:
          E2E_SKIP_ONLINE_FAIL: '1'
        run: |
          python scripts/e2e_test.py

      - name: Run e2e offline if norms exist (non-fatal if missing)
        continue-on-error: true
        env:
          E2E_MODE: offline
        run: |
          python scripts/e2e_test.py
